# Variables are defined in .env file
# to show the resolved docker-compose file, execute 
# docker-compose config

version: '3.7'

services:
  
  ecp-demo-data-server:
    build: .
    image: ecp-demo
    container_name: ecp-demo-data-server
    hostname: data-server
    networks:
      app_net:
    environment:
      # List of allowed ECP clients (application server).  
      - CLIENT_SYSTEMS=ecp-with-docker_ecp-demo-app-server_1;ecp-with-docker_ecp-demo-app-server_2;ecp-with-docker_ecp-demo-app-server_3
      # Path authority server certificate
      - CA_ROOT=/certificates/CA_Server.cer
      # Path to data server certificate
      - CA_SERVER=/certificates/data_server.cer
      # Path to private key of the data server certificate
      - CA_PRIVATE_KEY=/certificates/data_server.key
      # Path to Config-API file to initiliaze this IRIS instance
      - IRIS_CONFIGAPI_FILE=/home/irisowner/demo/data-server.json
    ports:
      - "81:52773"
    volumes:
      # Post start script - data server initilization.
      - ./init_datasrv.sh:/home/irisowner/demo/init_datasrv.sh
      # Mount certificates (see gen-certificates.sh to generate certificates)
      - ./certificates/app_server.cer:/certificates/data_server.cer
      - ./certificates/app_server.key:/certificates/data_server.key
      - ./certificates/CA_Server.cer:/certificates/CA_Server.cer
      # Mount config file
      - ./config-files/data-server.json:/home/irisowner/demo/data-server.json
      # IRIS License
      - ~/iris.key:/usr/irissys/mgr/iris.key
    command: -a /home/irisowner/demo/init_datasrv.sh
    

  ecp-demo-app-server:
    image: ecp-demo
    networks:
      app_net:
    environment:
      # Hostname or IP of the data server.
      - DATASERVER_IP=data-server
      - DATASERVER_NAME=data-server
      - DATASERVER_PORT=1972
      # Path authority server certificate
      - CA_ROOT=/certificates/CA_Server.cer
      - CA_CLIENT=/certificates/app_server.cer
      - CA_PRIVATE_KEY=/certificates/app_server.key
      - IRIS_CONFIGAPI_FILE=/home/irisowner/demo/app-server.json
    ports:
      - 52773
    volumes:
      # Post start script - application server initilization.
      - ./init_appsrv.sh:/home/irisowner/demo/init_appsrv.sh
      # Mount certificates
      - ./certificates/CA_Server.cer:/certificates/CA_Server.cer
      # Path to private key of the data server certificate
      - ./certificates/app_server.cer:/certificates/app_server.cer
      # Path to private key of the data server certificate
      - ./certificates/app_server.key:/certificates/app_server.key
      # Path to Config-API file to initiliaze this IRIS instance
      - ./config-files/app-server.json:/home/irisowner/demo/app-server.json
      # IRIS License
      - ~/iris.key:/usr/irissys/mgr/iris.key
    command: -a /home/irisowner/demo/init_appsrv.sh
  
networks:
  app_net:
    ipam:
      driver: default
      config:
        # APP_NET_SUBNET variable is defined in .env file
        - subnet: "${APP_NET_SUBNET}"
