# Variables are defined in .env file
# to show the resolved docker-compose file, execute 
# docker-compose config

version: '3.7'

services:
  
  datasrv:
    build: .
    image: ecp-demo
    container_name: data-server
    hostname: datasrv
    networks:
      app_net:
        ipv4_address: ${DATASRV_APP_NET}
    environment:
      # List of IP separeted by ";" of ECP client instance (application server)
      - CLIENT_SYSTEMS=${APPSRV1_APP_NET};${APPSRV2_APP_NET}
      - CA_ROOT=/certificates/CA_Server.cer
      - CA_SERVER=/certificates/data_server.cer
      - CA_PRIVATE_KEY=/certificates/data_server.key
      # Config-API file to initiliaze this instance
      - IRIS_CONFIGAPI_FILE=/opt/demo/data-server.json
    ports:
      - "85:52773"
    volumes:
      # Post start script - data server initilization.
      - ./init_datasrv.sh:/opt/demo/init_datasrv.sh
      # Mount certificates (see gen-certificates.sh to generate certificates)
      - ./certificates/app_server.cer:/certificates/data_server.cer
      - ./certificates/app_server.key:/certificates/data_server.key
      - ./certificates/CA_Server.cer:/certificates/CA_Server.cer
      # Instance config file
      - ./config-files/data-server.json:/opt/demo/data-server.json
      # IRIS License
      - ./iris.key:/dur/iris.key
    extra_hosts:
      - "appsrv1:${APPSRV1_APP_NET}"
      - "appsrv2:${APPSRV2_APP_NET}"
    command: ["--check-caps", "false", "--key", "/dur/iris.key", "-a", "/opt/demo/init_datasrv.sh"]

  appsrv1:
    image: ecp-demo
    container_name: app-server-1
    hostname: appsrv1
    networks:
      app_net:
        ipv4_address: ${APPSRV1_APP_NET}
    environment:
      - DATASERVER_IP=${DATASRV_APP_NET}
      - DATASERVER_NAME=DATASRV
      - DATASERVER_PORT=1972
      - CA_ROOT=/certificates/CA_Server.cer
      - CA_CLIENT=/certificates/app_server.cer
      - CA_PRIVATE_KEY=/certificates/app_server.key
      - REMOTE_DB_NAME=myappdata
      - IRIS_CONFIGAPI_FILE=/opt/demo/app-server.json
    ports:
      - "84:52773"
    volumes:
      # Post start script - application server initilization.
      - ./init_appsrv.sh:/opt/demo/init_appsrv.sh
      # Mount certificates
      - ./certificates/app_server.cer:/certificates/app_server.cer
      - ./certificates/app_server.key:/certificates/app_server.key
      - ./certificates/CA_Server.cer:/certificates/CA_Server.cer
      - ./config-files/app-server.json:/opt/demo/app-server.json
      # IRIS License
      - ./iris.key:/dur/iris.key
    extra_hosts:
      - "datasrv:${DATASRV_APP_NET}"
    command: ["--check-caps", "false", "--key", "/dur/iris.key", "-a", "/opt/demo/init_appsrv.sh"]
  
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "${APP_NET_SUBNET}"
